### ISSUE TITLE
Please release a version compatible with Bevy 0.17 on crates.io

### ISSUE THREAD

**Issue by rparrett** [rparrett/bevy_prototype_lyon#284]
Opening this so users have an obvious place to look for this info.

`bevy_prototype_lyon` has been updated for Bevy 0.16, but this work hasn't yet been merged and there hasn't been a release on crates.io.

There's an existing PR for Bevy 0.17, but it doesn't seem to include some of the work from the branch that upgraded to Bevy 0.16.

In the meantime, users can add the crate as a git dependency using my branch which fixes an important bug in the initial update 0.16 upgrade PR (#277), and also upgrades to 0.17.

Add the following to the dependencies section of your `Cargo.toml`.

edit: my fork is currently deleted while we work on transferring this repository and getting a release out.

```toml
[dependencies]
bevy_prototype_lyon = { git = "https://github.com/rparrett/bevy_prototype_lyon", branch = "bevy-0.17" }
```

Also, please let me know if you'd like some help with this or future releases. I wouldn't have time to do much development on the crate but could handle Bevy upgrades and occasional releases.
